### ISSUE TITLE
Implement as custom logger

### ISSUE THREAD

**Issue by dasjestyr** [gfoidl/trx2junit#23]
It would be great if you could implement this as a custom logger or something:

`dotnet test mysrc --logger:trx;trx2junit`

The bummer with this with some CI implementations is that if the test fails, the build fails immediately before I get a chance to convert the output

**Comment by gfoidl** [comment]
@dasjestyr thanks for the suggestion, but right now I feel this is out of scope for this project / tool. It would be better to create a separate logger-project following the instructions in [Create a test logger](https://github.com/Microsoft/vstest-docs/blob/master/docs/report.md#create-a-test-logger), that emits JUnit right away without the immediate steps (`logger -> trx -> trx2junit -> junit`).
Such an implementation could be based on [TrxLogger](https://github.com/Microsoft/vstest/blob/d9a0690801b872bd68ed0a91e9c3f8206992c45e/src/Microsoft.TestPlatform.Extensions.TrxLogger/TrxLogger.cs#L31), etc.

> with some CI implementations is that if the test fails, the build fails immediately

So far I didn't came accross such a limitation, because there were configuration knobs for that. Therefore I'm interested in these implementations. Would you be so kind to name an example?

PS: for my personal projects I like to have the _trx_-files, and only for the CI systems the need for _junit_-files arose. If the _trx_ would not be of interest, I would have gone the way via the explicit junit-logger.
