### ISSUE TITLE
Standard output per testcase

### ISSUE THREAD

**Issue by fjunqueira** [gfoidl/trx2junit#71]
Hey there! First and foremost, thank you for this tool. It's being really helpful on the project i'm working on. 

I have a question regarding the program output when parsing a TRX file that contains StdOut tags.

Here is the thing, if i open a TRX file where something was logged to the standard output, i get the following contents:

```xml
<UnitTestResult executionId="cceebcd2-10e0-4686-9d39-967f741560b8" testId="bd714b51-519d-8e5e-17f4-3146b90f62cf" testName="Test1" computerName="whatever" duration="00:00:00.0407230" startTime="2020-06-09T14:47:46.0000000-03:00" endTime="2020-06-09T14:47:46.0000000-03:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="cceebcd2-10e0-4686-9d39-967f741560b8">
      <Output>
        <StdOut>Hello, world!</StdOut>
        <ErrorInfo>
          <Message>  Expected is &lt;System.Int32[2]&gt;, actual is &lt;System.Int32[5]&gt;
               Values differ at index [0]
               Expected: 4
               But was:  0
          </Message>
          <StackTrace>   at Tests.Test1() in /home/fabio/workspace/sample/Tests.cs:line 16
          </StackTrace>
        </ErrorInfo>
      </Output>
</UnitTestResult>
```
Notice that there is a StdOut tag with the contents that were logged for a specific unit test.

I was looking at the xml generated by JUnit in a Java project, and i noticed that it behaves similarly. Take a look at this example:

```xml
<testcase name="test1" classname="Tests" time="0.006">
    <failure message="array lengths differed, expected.length=2 actual.length=5" type="java.lang.AssertionError">java.lang.AssertionError: array lengths differed, expected.length=2 actual.length=5
	at Tests.test1(Tests.java:10)
    </failure>
    <system-out><![CDATA[Hello World!]]></system-out>
</testcase>
```

There is a system-out tag with the contents logged at a specific test case.

If i attempt to run trx2junit on the first file i mentioned, the output will group all the standard outputs in a generic system-out tag. 

Is this the correct behavior? When looking at the [code](https://github.com/gfoidl/trx2junit/blob/c99d0ce8f7f7a5e31a7e721aed7c38a164bc7b7b/source/trx2junit/Internal/trx2junit/JUnitTestResultXmlBuilder.cs#L51), it seems that this behavior is on purpose, but it seems to me that mapping the contents in UnitTestResult -> StdOut tag to testcase -> system-out would make more sense. Am I right?

Thank you for your time!

**Comment by gfoidl** [comment]
> Am I right?

Yes, that seems more correct.

I can't remember why it was done that way it is, but there was a reason. Maybe it's the parser in CircleCI (the root-reason why I built this tool), to not show std-out otherwise correctly.

So the tool should change to keep the std-out at the testcase **instead** of aggregating them. 
Or should the std-out still be aggregated (additional)?

Maybe there should be a cli-option. So my suggestion -- based on your input -- is:

* keep the std-out per testcase (it's the correct behavior and should be the default)
* if `--aggregate-std-out` is set, then additionally aggregate
* if `--aggregate-std-out-only` is set, just aggregate (current behavior)

So for any parser the correct behavior can be set.

I need to take a look in the JUnit-xml specs to see for what the "generic std-out" is intended for.
Maybe tomorrow I have time to prepare a fix for this.

Thanks for pointing out!

**Comment by fjunqueira** [comment]
I think it still should be aggregated.

I found this [link](https://llg.cubic.org/docs/junit/) documenting the xml format, and apparently the "generic std-out" is meant to aggregate all the output from the testsuit.

**Comment by gfoidl** [comment]
Thanks, I read it the same way -- when the _testcase_ executed it implies that the _testsuite_ is executed.

**Comment by gfoidl** [comment]
Almost done...

>  there was a reason

The reason is that the used [schema](https://github.com/gfoidl/trx2junit/blob/master/schemas/junit.xsd) doesn't allow such an element. https://github.com/gfoidl/trx2junit/blob/2c9b02367ff9edd352be79ae17bef5b4525f058c/schemas/junit.xsd#L78-L141

[jenkins-junit.xsd](https://github.com/gfoidl/trx2junit/blob/master/schemas/jenkins-junit.xsd) (which was added later) allows it though:
https://github.com/gfoidl/trx2junit/blob/2c9b02367ff9edd352be79ae17bef5b4525f058c/schemas/jenkins-junit.xsd#L64-L79
