### ISSUE TITLE
make internal types (like Trx2JunitTestResultXmlConverter) public

### ISSUE THREAD

**Issue by juwens** [gfoidl/trx2junit#97]
### Summary
I wanted to adjust the behavior slightly. (Write the message attribute in system-out, because gitlab ignores message attribute).
It was not possible, because the Trx2JunitTestResultXmlConverter and xml Models are internal.
That's a pitty, because the rest of this little tool is great.

**Comment by gfoidl** [comment]
These types are internal as they are implementation details, subject to change, and hence will / should remain internal.
If they would be made public, then any change on their public contract would be a breaking change.

> Write the message attribute in system-out, because gitlab ignores message attribute

What if something like this is supported by default?
E.g. via option that states "gather all messages attributes and write to std-out"?
Would this satisfy your usecase?

Besides that you have the possibility to fork the project and make adjustments for your need.
(Although I'd prefer the aforementioned approach, so that more users can profit from such a change).

**Comment by juwens** [comment]
Thanks for the reply.
I unterstand your standpoint.
I try to provide a PR with the switch if time allows it.

**Comment by gfoidl** [comment]
Let's keep the issue open until it's resolved.

>  I try to provide a PR with the switch if time allows it.

👍🏻 perfect!
